services:
  db:
    build:
      context: ./src/db
      dockerfile: db.dockerfile
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urlshortener
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./src/backend
      dockerfile: backend.dockerfile
    container_name: url-shortener-backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=appsecret
      - MYSQL_DATABASE=urlshortener
    volumes:
      - ./src/frontend/templates:/app/templates
      - ./src/frontend/static:/app/static

  frontend:
    build:
      context: ./src/frontend
      dockerfile: frontend.dockerfile
    container_name: url-shortener-frontend
    ports:
      - "9090:80"

volumes:
  mysql-data:

